[project]
name = 'amcoin'
description = 'AMCOIN fungible token smart contract (SIP-010)'
authors = ['NKECHI OKOYE']
telemetry = true
cache_dir = '.\\.cache'
requirements = []
[contracts.amcoin]
path = 'contracts/amcoin.clar'
clarity_version = 3
epoch = 'latest'

[contracts.sip-010-ft-trait]
path = 'contracts/sip-010-ft-trait.clar'
clarity_version = 3
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
